future: true
permalink: /:title/
url: http://Dxiaocai666.github.io
name: 菜园子
author: Dxiaocai
qq: 1582872960
email: dengyt5@mail2.sysu.edu.cn

duoshuo: yourname
beian: 
cnzz: 
weibo: 
github: Dxiaocai666
about: "这里是 邓小菜 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
