future: true
permalink: /:title/
url: http://Dxiaocai666.github.io
name: Dxiaocaiauthor: 邓玉婷
qq: 1582872960
email: dengyt5@mail2.sysu.edu.cn

duoshuo: yourname
beian: 
cnzz: 
weibo: 
github: yourID
about: "这里是 Your 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
